### ISSUE TITLE
comparing exclosures to controls

### ISSUE THREAD

**Issue by emchristensen** [weecology/LDA-kratplots#2]
We need to compare the locations of the changepoints from the analysis on the krat exclosure plots to the changepoints on the control plots. So far our plan is to get 95% credible intervals for each changepoint, and compare the overlap. Other ideas?

**Comment by ha0ye** [comment]
One aspect of this comparison that I would like to see is some way of looking for similarities/differences among the topics along with the number and timing of changepoints.

For instance, suppose that the changepoints line up exactly, but that the topics are different? Does this mean that the change is driven purely by extrinsic factors (flood, drought, etc.) but that the communities on controls is just completely different from exclosures? Or is it possible that there is a great deal of similarity among the rodent communities (excepting the K rats of course), which results in the LDA picking out different topics?

Something to think about for how to interpret the results ecologically, as the methods are being worked on?
